### ISSUE TITLE
Internal Panic in pointer analysis when trying to analyse a project

### ISSUE THREAD

**Issue by SPoint42** [stripe/safesql#14]
Hi,

I was trying to analyse this project : github.com/pydio/cells

and got this error: 

Any idea ? 

_eagle@XXXXXX:~/go/src/github.com/pydio/cells$ /home/eagle/go/bin/safesql  -q .
		Internal panic in pointer analysis:
goroutine 1 [running]:
runtime/debug.Stack(0x24, 0x0, 0x0)
	/usr/lib/go-1.10/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/lib/go-1.10/src/runtime/debug/stack.go:16 +0x22
golang.org/x/tools/go/pointer.Analyze.func1(0xc4201f1be0)
	/home/eagle/go/src/golang.org/x/tools/go/pointer/analysis.go:227 +0x110
panic(0x6844e0, 0xc4c38e1f10)
	/usr/lib/go-1.10/src/runtime/panic.go:502 +0x229
golang.org/x/tools/go/pointer.(*analysis).callEdge(0xc4cb5fc8c0, 0xc4d0c85d40, 0xc4c571af80, 0xcb179)
	/home/eagle/go/src/golang.org/x/tools/go/pointer/analysis.go:368 +0x7cc
golang.org/x/tools/go/pointer.Analyze(0xc4cb8c4280, 0x0, 0x72aa20, 0xc4c38e1fc0)
	/home/eagle/go/src/golang.org/x/tools/go/pointer/analysis.go:354 +0x6fd
main.main()
	/home/eagle/go/src/github.com/stripe/safesql/safesql.go:114 +0xa7e
error performing pointer analysis: internal error in pointer analysis: callEdge dynamic function call -> n831865: not a function object (please report this bug)_

**Comment by fho** [comment]
I'm getting the same error when running safesql for our applications
